### PR TITLE
fix: handle pseudo-class in middle of selector

### LINKED ISSUE #51: :focus-within sometimes gives an invalid selector warning
The pseudo-class `:focus-within` sometimes gives an invalid selector warning.

For example, this code `.group:focus-within .group-focus\:block {...}` produces:

```
  .group:focus-within .group-focus\ -> '.group:focus-within .group-focus\' is not a valid selector
```

I doubt that any class with `:focus-within` will ever be used in critical CSS, but those warnings create some noise. A workaround if to set `logLevel` to "error".

This issue probably causes https://github.com/GoogleChromeLabs/critters/issues/47.

On the other side, I am sure some simple selectors like `foo::focus-within` are accepted.

### PR DESCRIPTION
**Pull request by alan-agius4**
**fix: handle pseudo-class in middle of selector**

At the moment critters doesn't correctly handle pseudo-class in the middle of the selector string and pseudo-class which take a value such as `:not`

Example
```
.mat-slider:hover .mat-slider-track-background
.mat-slider-min-value:not(.mat-slider-thumb-label-showing):hover.mat-slider-disabled .mat-slider-thumb
```

More context about CSS pseudo-classes can be found https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

Closes #51

**fix: handle classes with colons**

Class names can have `:` if they are escapped. Example: `.flex\:box`

### CODE REVIEW

**Comment by alan-agius4** [comment]
@janicklas-ralph mind taking a look at this?

**Review by developit — APPROVED** [review]

File: src/index.js [hunk 1]
```diff
@@ -460,7 +460,7 @@ export default class Critters {
             // Strip pseudo-elements and pseudo-classes, since we only care that their associated elements exist.
             // This means any selector for a pseudo-element or having a pseudo-class will be inlined if the rest of the selector matches.
             if (sel !== ':root') {
-              sel = sel.replace(/(?:>\s*)?::?[a-z-]+\s*(\{|$)/gi, '$1').trim();
+              sel = sel.replace(/(\\?)::?[a-z-]+(\(.+?\))?\s*/gi, (match, p1) => p1 === '\\' ? match : ' ').trim();
```
Comment (developit) [inline src/index.js:463]: Here's a few more cases that could be handled:
- `bar:not(.foo)` - we delete `:not(.foo)`, which is not a pseudo-selector and should be preserved/used
- `bar:not(:hover)` - deleting `:hover` produces `bar:not()`, which would be invalid
- `bar:not(:not(.foo))` - not safe to remove this

The following lookahead/lookbehind version should handle them:
```suggestion
              sel = sel.replace(/(?<!\\)::?[a-z-]+(?![a-z-(])/gi, '').replace(/::?not\(\s*\)/g, '').trim();
```

Comment (alan-agius4) [reply src/index.js:463]: Indeed, this is better.

**Comment by alan-agius4** [comment]
@developit, changes done. PTAL.

**Review by developit — APPROVED** [review]
