### PR TITLE
fix: Adding in missing getter for `document.head`

### LINKED ISSUE #69: Refactor: additionalStylesheets appears broken
Using the config property `additionalStylesheets` with the refactor branch, e.g. `critters@0.0.7` will lead to the following error where `document.head` is undefined. 

```
(node:30702) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'appendChild' of undefined
    at /Users/mswaagman/projects/public/next.js/examples/with-linaria/node_modules/critters/dist/critters.js:9955:25
    at Array.forEach (<anonymous>)
    at /Users/mswaagman/projects/public/next.js/examples/with-linaria/node_modules/critters/dist/critters.js:9952:17
```

### PR DESCRIPTION
**Pull request by rschristian**
Closes #69 

Simply missing a getter for `head`. 

Full stack trace of the error that this fixes. The one in the linked issue is fairly outdated and the error position is no longer correct:

```
TypeError: Cannot read property 'appendChild' of undefined
    at ../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js:199:23
        at Array.map (<anonymous>)
    at ../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js:195:24
        at Array.forEach (<anonymous>)
    at CrittersWebpackPlugin.embedAdditionalStylesheet (../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js:188:48)
    at CrittersWebpackPlugin.process (../../node_modules/critters/dist/critters.js:633:12)
    at handleHtmlPluginData (../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js:85:14)
    at eval (eval at create (../../node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:13:1)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (../../node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:2:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (../../node_modules/tapable/lib/Hook.js:154:20)
    at ../../node_modules/html-webpack-plugin/index.js:267:70
```

Adds a couple tests to ensure `additionalStylesheets` works.

### CODE REVIEW

**Review by janicklas-ralph — APPROVED** [review]

File: packages/critters-webpack-plugin/test/fixtures/additionalStylesheets/index.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import './style.css';
+
+document.body.appendChild(document.createTextNode('this counts as SSR'));
+
+import('./chunk.js').then();
```
Comment (rschristian) [inline packages/critters-webpack-plugin/test/fixtures/additionalStylesheets/index.js:5]: If there's a slightly less awkward way to create another chunk, certainly let me know. This was just to generate another stylesheet

File: packages/critters-webpack-plugin/test/__snapshots__/index.test.js.snap [hunk 2]
```diff
@@ -161,6 +161,39 @@ exports[`Inline <style> pruning should remove unused rules 1`] = `
...
+exports[`options { additionalStylesheets:["*.css"] } should match snapshot 1`] = `
+"<!DOCTYPE html><html><head>
+    <title>Additional Stylesheet CSS Demo</title>
+  <style>html {
+  padding: 0px;
+}
+
+html {
+  padding: 0px;
+}
```
Comment (rschristian) [inline packages/critters-webpack-plugin/test/__snapshots__/index.test.js.snap:173]: Unfortunately this is correct at the moment, and Critters no longer dedupes, see #88

**Comment by rschristian** [comment]
@developit Sorry to ping, but any chance you could take a look at this? This is the only remaining blocker for upgrading to HtmlWebpack v4 in preact-cli

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
@rschristian published as [critters@0.0.15](https://github.com/GoogleChromeLabs/critters/releases/tag/critters-0.0.15)!

**Comment by rschristian** [comment]
Thanks!
